### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by xhebox** [xhebox/fastc#3]
- [ ] well document the format itselt
- [x] make it a shared lib
- [x] shared lib name releated
- [ ] binding for other languages
- [ ] handle fasta/q <=> fastc
- [ ] a front-end for viewing fastc

**Comment by xhebox** [comment]
# 格式简明说明

| 大小 | 内容 |
| - | - |
| 1 byte | 起始是atcg模式还是简并模式 |
| n byte | 编码后atcgu碱基序列 |
| 1 byte | 截断符号 |
| 1 byte | 截断前1byte, 有几个碱基, 以防三个碱基被认为是XXXA四个碱基 |
| n byte | 简并或其他信息 |
| 1 byte | 截断符号 |
| n byte | 编码后atcgu碱基序列 |
| .... | .... |
| 1 byte | 截断符号 |
| n byte | 简并或其他信息 |

遇到截断符号就切换存取模式.

如果结尾的时候, 最后存取的是atcg序列:

| 大小 | 内容 |
| - | - |
| n byte | 编码后atcgu碱基序列 |
| 1 byte | 截断前1byte, 有几个碱基, 以防三个碱基被认为是XXXA四个碱基 |

# atcg模式

| 大小 | 内容 |
| - | - |
| 2 bits | 碱基1 |
| 2 bits | 碱基2 |
| 2 bits | 碱基3 |
| 2 bits | 碱基4 |

一个byte可以编入四个atcgu符号. 对于和截断字符相同的情况, 放在下种模式中处理.

# 简并模式

| 大小 | 内容 |
| - | - |
| 4 bits | 符号的数量 |
| 4 bits | 简并符号 或 与截断符号相同的CCCC序列 |

# 编码表

| 符号 | 编码 |
| - | - |
| atcg模式 | 0x1 |
| 简并模式 | 0x2 |
| 截断符号 | 0xFF |
| A | 0x0 |
| T/U | 0x1 |
| G | 0x2 |
| C | 0x3 |
| R | 0x0 |
| Y | 0x1 |
| K | 0x2 |
| M | 0x3 |
| S | 0x4 |
| W | 0x5 |
| B | 0x6 |
| D | 0x7 |
| H | 0x8 |
| V | 0x9 |
| N | 0xA |
| - | 0xB |
| 与截断符号相同的ATCG序列, 也就是CCCC | 0xC |

ps: T/U不可能同时出现, 合并.
